
a=input("enter value of a: ")
b=input("enter value of b: ")
a=int(a)
b=int(b)
print(f"value of a is {a}")
print(f"value of b is {b}")
print("sum is " +str(a+b))
print("Difference is " +str(a-b))
print("product is " +str(a*b))
print("division is " +str(a/b))
